### ISSUE TITLE
Addon's ember-source incompatible with Ember 5

### ISSUE THREAD

**Issue by Elawphant** [adopted-ember-addons/ember-keyboard#744] opened 2023-06-27 15:47 UTC
Please fix the ember-source dependency

**Comment by SergeAstapov** [comment] 2023-06-27 15:57
@Elawphant sorry could you be little bit more specific? `ember-source` is not listed in `dependencies` nor `peerDependencies` of this addon see https://github.com/adopted-ember-addons/ember-keyboard/blob/master/addon/package.json

**Comment by Elawphant** [comment] 2023-06-27 15:59
hmm. very strange.
I have removed my node_modules and trying to reinstall with all fresh dependencies. I got an error with this one too. But seems it should have not have risen.

**Comment by NullVoxPopuli** [comment] 2023-09-06 21:32
looks like this is resolved?

**Comment by SergeAstapov** [comment] 2023-09-07 14:38
Closing until we have a reproduction as issue reported here seems unrelated to `ember-keyboard`

**Closed by SergeAstapov** 2023-09-07 14:38 UTC
